Gs bug 87
bee-travels/bee-travels-node pull request #88
Opened 2020-01-30 18:55 UTC by Grant-Steinfeld

@max-shapiro32 please take a look at issue 87 bug fix for 501 error on currency exchange when base currency is invalid = now all tests pass as well as manual test confirm this is now a 404

2020-02-03 15:03 UTC, MaxShapiro32 requested changes

2020-02-03 15:03 UTC, MaxShapiro32 commented on src/currencyexchange/src/lib/logger.js
> +import winston from 'winston';
Instead of using `winston` for logging can you use [pino](https://github.com/pinojs/pino)? It is the logger that the Node.js people recommend we use.

2020-02-03 15:03 UTC, MaxShapiro32 commented on src/currencyexchange/src/services/serviceHandler.js
> +        throw new NotFoundError(`no country code ${baseCode}`);
Does this ever get called? I would think it gets handled on line 24

2020-02-03 15:14 UTC, Grant-Steinfeld commented on src/currencyexchange/src/lib/logger.js
> +import winston from 'winston';
I am not familiar with pino yet but will look into it and replace winston

2020-02-03 21:42 UTC, Grant-Steinfeld commented on src/currencyexchange/src/services/serviceHandler.js
> +        throw new NotFoundError(`no country code ${baseCode}`);
I will add a log statement in this block check to see if it is indeed redundant

2020-02-04 08:29 UTC, Grant-Steinfeld commented on src/currencyexchange/src/services/serviceHandler.js
> +        throw new NotFoundError(`no country code ${baseCode}`);
yes it is called, I made the error messages more explicit/helpful to show both cases are indeed called

2020-02-04 08:31 UTC, Grant-Steinfeld commented on src/currencyexchange/src/lib/logger.js
> +import winston from 'winston';
yes I agree, we will use `pino` instead - I will create a new feature branch and make a PR from there.

2020-02-04 18:53 UTC, MaxShapiro32 commented
@Grant-Steinfeld The `404` response code should also be documented in the Swagger

2020-02-04 20:14 UTC, MaxShapiro32 commented on src/currencyexchange/src/lib/logger.js
> +import winston from 'winston';
Pino is now being used

2020-02-04 20:15 UTC, MaxShapiro32 commented on src/currencyexchange/src/services/serviceHandler.js
> +        throw new NotFoundError(`no country code ${baseCode}`);
That makes more sense. Thanks for adding that!

2020-02-04 20:17 UTC, MaxShapiro32 approved these changes
Looks good to me!

2020-02-04 20:20 UTC, merged